### ISSUE TITLE
Civi Core upgrade to 5.31 breaks CiviCase (latest)

### ISSUE THREAD

**Issue by pbarmak** [compucorp/uk.co.compucorp.civicase#654]
We are having issues upgrading CiviCRM core to 5.31. I wrote about it in this stackexchange post: https://civicrm.stackexchange.com/questions/38231/version-5-31-0-seems-to-break-the-civicase-extension

I have since updated CiviCase to the latest git commit as of this morning, and then also upgraded core to 5.31.1, hoping that something was fixed in core. This didn't help. We get the same angularjs errors in our dev console (both Firefox and Chrome) and case functionality is broken. We don't see other general errors, so I believe this is specific to CiviCase and maybe the integration with the latest angularjs on core (which was updated in 5.31)?

I have cleared the dyn directory multiple times, and cleared normal caches, and the issue persists. I am not sure how to debug further, but can provide logs if needed.

Using:
Civi core: 5.31.1
CiviCase: 1.9.7 (commit fad14ad9f297d45c4798eb709220cc4d8512ebf8)
Shoreditch: 1.0.0-beta.4 (commit 1b2598b38c3720fedab19ff107e5e56c43b3346a)

**Comment by tunbola** [comment]
Hi @pbarmak , Thanks for raising this issue. We will investigate and fix in upcoming civicase versions. We'll keep you updated on this issue.

**Comment by pbarmak** [comment]
Just as an update, I tried upgrading to Civi core version 5.32.1 since that is now out, but I have the same issues. I have also updated to the latest git commit of CiviCase. So this issue still exists. Only Civi core 5.30 seems to work in our environment, nothing beyond that.

**Comment by pbarmak** [comment]
Additional update: I have now just performed a completely clean install of Drupal 7, CiviCRM 5.32.1, latest git clone of ShoreDitch and it's companion theme, and the latest git clone of CiviCase. The only data in Civi is the sample data. And I continue to receive these angularjs errors. This leads me to believe it's not an issue with my particular Civi configuration, but something more general. It feels like some compatibility issue with whatever angularjs is in the latest version of Civi.

**Comment by reneolivo** [comment]
@pbarmak sorry for the slow response. We have investigated this issue and the problem is that CiviCRM updated the angular version from 1.5 to 1.8. Right now we are looking on fixes for multiple areas that broke with the update but we are still not sure when we are going to update.

If civicase is a key part of your CiviCRM installation we'd recommend using version 5.28 in the meantime.

**Comment by pbarmak** [comment]
@reneolivo , I just wanted to check in and see if there is an update on this issue.

Also, if you know of certain calls that are causing the issue, would you mind pointing me at them? I'd like to see if I can update my instance to at least get us to a point where we can update core. There are other fixes in core that we need, but we also rely heavily on this extension. Let me know if it's certain calls that are broken, I'd be happy to try and fix things on our end for now. If it's a much bigger problem than a few calls to update, I understand. Thank you.

**Comment by reneolivo** [comment]
Hello @pbarmak, there are good news.

We'll start working on this tomorrow. We should get the errors fixed in a week or two, although I'm not sure when they are going to be released.

We have a preliminary list of 4 relatively easy issues that can be fixed right away, but we still need to determine if this is enough or there are more things that are required and that will be determined after running extensive testing.

I'll have this fixes ready in a branch tomorrow and can point you to the branch (which will only work on CiviCRM 5.31) in case you want to test it for yourself. We don't really recommend you using this in production though. Even if the extension will appear to be working, it might have bugs that are not easily detected.

**Comment by albionbrown** [comment]
Hi @reneolivo, is there any more updates on the fix?

**Comment by MikeyMJCO** [comment]
> Hi @reneolivo, is there any more updates on the fix?

There's activity in recent branches so there's working happening but as it stands this is unusable on secure versions of CiviCRM. Recommending people stay on 5.28 isn't a workable solution.

**Comment by deb1990** [comment]
This has been fixed in the latest release.

**Comment by pbarmak** [comment]
There still seems to be a problem. I will also open a separate case, as I'm not sure if this one can be reopened.

After upgrading both CiviCase and Core (to 5.35.1), when we go to a specific Contact record and click on Activities, nothing shows up even though there are activities. If I disable CiviCase, activities show up (in the old table listing format/style). My dev console shows the following error with CiviCase is enabled and I refresh the Activities page:

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.8.0/$injector/modulerr?p0=civicaseActivitiesTab&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.8.0%2F%24injector%2Fmodulerr%3Fp0%3Dcivicase%26p1%3D%255B%2524injector%253Aunpr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.8.0%252F%2524injector%252Funpr%253Fp0%253DActivityFormsProvider%250AF%252F%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A7%253A168%250Afb%252Fp.%2524injector%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A46%253A468%250Ad%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A44%253A197%250Ae%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fa…
    Angular 7
    jQuery 9
    refresh crm.ajax.js:303
    jQuery 8
    refresh crm.ajax.js:284
    jQuery 5
    loadPage crm.ajax.js:372
    <anonymous> TabHeader.js:52
    jQuery 38
    <anonymous> TabHeader.js:56
    jQuery 8
angular.js:99

```

**Comment by albionbrown** [comment]
@pbarmak Everytime I've had that error it's been something to do with my path settings in civicrm.settings.php. Try playing with those!

**Comment by mlutfy** [comment]
@deb1990 Would it be possible to point to the commit fixing this? I'm still having issues, and looking at the latest commits, could not see where the fix is.

**Comment by reneolivo** [comment]
@mlutfy what error are you referring to? The same as @pbarmak?

How do you install your site?

**Comment by mlutfy** [comment]
@reneolivo Yep, same error as @pbarmak 

It's a WP install on 5.36 (not using composer, just standard CiviCRM).

**Comment by reneolivo** [comment]
Thanks @mlutfy. @pbarmak are you also using WordPress?

**Comment by mlutfy** [comment]
Some confusing leads..

* I tried downgraded AngularJS to 1.5.11 (it had helped previously), but in this specific case (Contact Activities), it does not fix the issue.
* The bug only happens when browsing as an admin, not as a regular staff/contributor user.

So I guess it's a bit fishy, and might be something else causing issues.
